# -*- coding: utf-8 -*-
"""Boxplot.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RoZRaTYmanw5BLofuxzLoLIE0XW1BFIZ
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/gdrive')
path = '/content/gdrive/My Drive/Visualization/Data/'
path_img = '/content/gdrive/My Drive/Visualization/Images/'

# loading and preparing data
df = pd.DataFrame({'a': np.random.randn(2000).tolist(),
                   'b': [i+1 for i in np.random.randn(2000).tolist()],
                   'c': [i+1 for i in np.random.randn(2000).tolist()],
                   'd': [i+1 for i in np.random.randn(2000).tolist()],
                   'e': [i+2 for i in np.random.randn(2000).tolist()]})

# color labels setting 
colors = {'a':'#384794','b':'#4F8B46', 'c':'#BF3535'}
color = ['RdBu_r']

# plot size setting
fig, ax = plt.subplots(figsize = (4,6))

# drawing Plot
sns.boxplot(x = df.columns, y = [df.a,df.b,df.c,df.d,df.e] ,palette=color[0])

# title and size
ax.set_title('Title',fontsize=14, family='DejaVu Sans', loc='center', pad=5)

# x,y label and size
# labelpad: Spacing in points between the label and the x-axis
plt.xlabel('x-label', fontsize = 14, labelpad=8)
plt.ylabel('y-label', fontsize = 14, labelpad=8)

# save image as pdf to path folder
# bbox in inches, only the given portion of the figure is saved, figure out the tight bbox of the figure
plt.savefig(path_img+'boxplot.pdf', bbox_inches='tight')
# showing the image
plt.show()

