# -*- coding: utf-8 -*-
"""Violin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BtQ49F36bWyExdw3qPjDeLwZtNJ0Yu8r
"""

import numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
from google.colab import drive
drive.mount('/content/gdrive')
pathconf = '/content/gdrive/My Drive/Visualization/parameter.conf'
path = '/content/gdrive/My Drive/Visualization/Data/'
path_img = '/content/gdrive/My Drive/Visualization/Images/'

# loading and preparing data
with open(path+'Iris.csv','r') as f:
    data = pd.read_csv(f)

# color labels setting 
colors = {'Iris-setosa':'#384794','Iris-versicolor':'#4F8B46', 'Iris-virginica':'#BF3535'}
color = ['Blues', 'white']

# plot size setting 
fig, ax = plt.subplots(figsize =(7, 5)) 

# drawing plot
a = sns.violinplot(ax = ax, x = data["Species"],  
                  y = data["SepalLengthCm"],palette=color[0])

# background setting 
sns.set(style=color[1])

# title and size
a.axes.set_title("Title",fontsize=20,pad = 10)

# x,y labels and size
a.set_xlabel("X Label",fontsize=15)
a.set_ylabel("Y Label",fontsize=15)

# tick labels and size
a.tick_params(labelsize=12)

# here is "True", "False" removing top and right borders
ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)

# save image as pdf to path folder
# bbox in inches, only the given portion of the figure is saved, figure out the tight bbox of the figure
plt.savefig(path_img+'violin.pdf', bbox_inches='tight')
# showing the image
plt.show()

"""# grouped violin"""

# loading data
tips = sns.load_dataset("tips")

# color labels setting 
color = ['RdBu_r', 'whitegrid']

# plot sizef setting 
ig, ax = plt.subplots(figsize =(9, 7)) 

# drawing plot
a = sns.violinplot(x="day", y="total_bill", hue="smoker", data=tips, palette=color[0], split=True)

# background setting
sns.set(style=color[1])

# title and size
a.axes.set_title("Title",fontsize=20,pad = 10)

# x,y labels and size
a.set_xlabel("X Label",fontsize=15)
a.set_ylabel("Y Label",fontsize=15)

# tick labels and size
a.tick_params(labelsize=12)

# here is "True", "False" to removing top and right borders
ax.spines['top'].set_visible(True)
ax.spines['right'].set_visible(True)

# save image as pdf to path folder
# bbox in inches, only the given portion of the figure is saved, figure out the tight bbox of the figure
plt.savefig(path_img+'violin_group.pdf', bbox_inches='tight')
# showing the image
plt.show()

